import type { Locale } from '../i18n'

const chinese = {
  'Local transcription.': '本地转写。',
  'No account.': '无需账号。',
  'No subscription.': '无需订阅。',
  'Download a model. Transcribe offline.': '下载模型，即可离线转写。',
  'Optional cloud transcription · Bring your own API key.': '云端转写可选 · 使用自己的 API key',
  'Why local matters': '为什么选择本地转写',
  'Local transcription. No signup.': '本地转写，无需注册。',
  'Download a model and transcribe locally without registering or configuring an API key. You can also use cloud transcription through Groq or OpenAI with your own API key.': '下载模型后即可在本地转写，无需注册或配置 API key。偏好云端？也可以使用自己的 API key，接入 Groq 或 OpenAI。',
  'Optional cloud features': '可选的云端功能',

  'Skip to content': '跳到正文',
  'Primary navigation': '主要导航',
  'SayType home': 'SayType 首页',
  'Page sections': '页面章节',
  'How it works': '使用方法',
  'Product': '产品',
  'Privacy': '隐私',
  'Updates': '产品更新',
  'Layout preview': '布局预览',
  '1 · Editorial': '1 · 编辑式布局',
  '2 · Product stage': '2 · 产品展示布局',
  'Exit layout preview': '退出布局预览',
  'Exit preview': '退出预览',
  'Download for Mac': '下载 Mac 版',
  'Download for Windows': '下载 Windows 版',
  'Download for Linux': '下载 Linux 版',
  'Download SayType for Mac': '下载 Mac 版 SayType',
  'Download SayType for Windows': '下载 Windows 版 SayType',
  'Download SayType for Linux': '下载 Linux 版 SayType',
  'View downloads': '查看下载',
  'View SayType downloads': '查看 SayType 下载',
  'Preparing download…': '正在准备下载…',
  'Speak freely.': '自在说话。',
  'Keep your words close.': '文字留在身边。',
  'Your voice.': '说出所想。',
  'Right where': '文字就到',
  'you work.': '光标所在。',
  'Hold Ctrl+Shift, speak, release.': '按住 Ctrl+Shift，说话，然后松开。',
  'Voice typing in the apps you already use.': '在你正在使用的应用里，直接用声音输入。',
  'See how it works': '看看如何使用',
  'Local transcription. No account. No subscription.': '本地转写，无需账号，无需订阅。',
  'View full-size SayType Dictation Settings screenshot': '查看 SayType 听写设置原图（英文界面）',
  'SayType main window showing Dictation Settings and available transcription engines': 'SayType 主窗口：听写设置与可用转写引擎（英文界面）',
  'One shortcut, every app': '一个快捷键，随处输入',
  'Hold. Speak. Release.': '按住，说话，松开。',
  'One physical gesture carries a thought all the way back to your cursor.': '一个简单动作，把想法变成光标处的文字。',
  'Hold': '按住',
  'Press Ctrl+Shift in the app where you want to write.': '在你想输入文字的应用中，按住 Ctrl+Shift。',
  'Speak': '说话',
  'SayType listens while a compact prompt keeps you oriented.': 'SayType 开始录音，小巧的提示窗显示当前状态。',
  'Release': '松开',
  'Your transcript returns to the text field that already has focus.': '转写完成后，文字自动填入当前聚焦的输入框。',
  'On-device transcription': '设备端转写',
  'Optional cloud translation': '可选云端翻译',
  'Local History & retry': '本地历史记录与重试',
  'The product': '产品功能',
  'Ready when you are. Invisible when you’re not.': '随时待命，不打扰工作。',
  'In local mode, SayType turns speech into text on your Mac and inserts it at your cursor. Choose your engine once, then keep working where you are.': '在本地模式下，SayType 在你的 Mac 上把语音转成文字，并输入到光标所在位置。选好引擎，就能继续手头的工作。',
  'View full-size SayType App Settings screenshot': '查看 SayType 应用设置原图（英文界面）',
  'SayType main window showing App Settings, appearance and software updates': 'SayType 主窗口：应用设置、外观与软件更新（英文界面）',
  'App Settings. Make yourself at home.': '应用设置，按你的习惯调整。',
  'View full size': '查看原图',
  'Global hold-to-record hotkey': '全局按住录音快捷键',
  'Hold Ctrl+Shift to record, release to stop, and keep your hands near the keyboard.': '按住 Ctrl+Shift 录音，松开停止，双手无需离开键盘。',
  'Active-app text insertion': '文字直接输入当前应用',
  'Transcribed text is sent back to the app and text field that already has your cursor.': '转写后的文字直接输入光标所在的应用和文本框。',
  '100% local transcription': '100% 本地转写',
  'Turn speech into text on your Mac. In local mode, your audio and transcript stay on your device.': '在你的 Mac 上把语音转成文字。本地模式下，音频和转写文字都留在设备上。',
  'Speak it. Write it in English.': '说出想法，写成英文。',
  'Hold Shift+Alt to translate speech into English through a cloud provider using your own API key.': '按住 Shift+Alt，使用你自己的 API key，通过云端服务将语音翻译成英文。',
  'Which local engine should I choose?': '我该选哪个本地引擎？',
  'Qwen3-ASR 0.6B is the recommended local model, with a ~1 GB one-time download. Qwen3-ASR 1.7B and Nemotron live transcription are experimental options. The larger Qwen model needs a ~2.52 GB download; performance varies with your hardware.': '推荐使用 Qwen3-ASR 0.6B 本地模型，首次需下载约 1 GB。Qwen3-ASR 1.7B 和 Nemotron 实时转写属于实验性选项。更大的 Qwen 模型需下载约 2.52 GB；实际性能取决于硬件。',
  'Your transcript, saved locally': '转写文字，保存在本地',
  'Copy saved transcripts from History. If transcription fails and audio was saved, retry it with your current engine.': '你可以从历史记录中复制已保存的转写文字。如果转写失败且录音已保存，可以使用当前引擎重新转写。',
  'Practical desktop controls': '桌面操作',
  'Input': '输入',
  'Uses your system’s default microphone': '使用系统默认麦克风',
  'Control': '控制',
  'Press Escape to cancel': '按 Escape 取消',
  'Presence': '运行方式',
  'Runs quietly from the menu bar': '在菜单栏中安静运行',
  'Change your input device in your operating system’s sound settings. Updates download in the background. Restart when you’re ready.': '在操作系统的声音设置中切换输入设备。更新会在后台下载，准备好后再重启安装。',
  'Local by design': '为本地使用而设计',
  'In local mode · on-device transcription': '本地模式 · 设备端转写',
  'Your words stay on your Mac.': '你的话，留在你的 Mac。',
  'In local mode, audio is processed on your Mac and transcripts are saved there. Neither is uploaded for transcription. Your everyday thoughts do not need a trip to someone else’s server.': '在本地模式下，音频在你的 Mac 上处理，转写文字也保存在那里，两者都不会为了转写而上传。日常想法，无需经过别人的服务器。',
  'Benefits of local transcription': '本地转写的优势',
  'Works offline': '离线也能用',
  'Download a local model once, then transcribe without an internet connection.': '首次下载本地模型后，即使没有网络也能转写。',
  'No subscription or word limits': '无需订阅，没有字数限制',
  'Local transcription needs no account or API key. No weekly allowance and no per-minute service fees.': '本地转写无需账号或 API key，没有每周额度，也没有按分钟收取的服务费。',
  'Transcribe first. Edit on your terms.': '先转成文字，再由你决定怎么改。',
  'Get your words as text. You decide whether to rewrite them, which tool to use, and what to share.': '先把你说的话转成文字。是否改写、使用什么工具、分享哪些内容，都由你决定。',
  'Optional cloud transcription and translation send audio to Groq or OpenAI using your own API key. Provider charges may apply.': '可选的云端转写和翻译会使用你自己的 API key，将音频发送给 Groq 或 OpenAI。服务商可能收取费用。',
  'Hold Shift+Alt to turn speech into English through a cloud provider. In local mode, translation setup asks for your consent before sending audio.': '按住 Shift+Alt，通过云端服务将语音翻译成英文。在本地模式下，翻译设置会先征得你的同意，再发送音频。',
  'macOS is the primary tested path. Windows and Linux builds remain experimental.': 'macOS 是主要经过测试的平台。Windows 和 Linux 版本仍处于实验阶段。',
  'Offline dictation. No account. No subscription.': '离线听写，无需账号，无需订阅。',
  'Your voice. No cloud required.': '用声音输入，无需云端。',
  'Download requirements': '下载与使用要求',
  'macOS primary': '主要支持 macOS',
  'Apple Silicon recommended for local dictation': '本地听写推荐使用 Apple Silicon',
  '~1 GB download for Qwen3-ASR 0.6B': 'Qwen3-ASR 0.6B 需下载约 1 GB',
  'Microphone and Accessibility permissions required': '需要麦克风和辅助功能权限',
  'Back to top': '返回顶部',
  'Voice to text. On your device.': '语音转文字，就在你的设备上。',
  'GitHub releases ↗': 'GitHub 发布记录 ↗',
}

type HomeCopyKey = keyof typeof chinese

export function homeCopy(locale: Locale) {
  return (key: HomeCopyKey): string => locale === 'zh' ? chinese[key] : key
}
